// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biupwukrttgwhzverbbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpdXB3dWtydHRnd2h6dmVyYmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NTQ1MDgsImV4cCI6MjA1NDQzMDUwOH0.CwHaeN94B_Z0j8pXtBPtPGxNUQ0alXWKG27pYoUM37s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);